import json
from datetime import date

import gradio as gr

from llm_integration import get_summary_candidate_models


MARKET_OPTIONS = ["DE", "UK", "FR"]
MONTH_OPTIONS = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
]
YEAR_OPTIONS = [str(year) for year in range(2024, 2031)]

SECTION_OPTIONS = [
    "executive_summary",
    "market_trends",
    "platform_updates",
    "competitor_intelligence",
    "independent_artist_economy",
    "market_opportunities",
    "data_sources_used",
]


MOCK_CONTENT_PIPELINE_RESPONSE = {
    "report": {
        "full_text": (
            "BELIEVE MARKET INTELLIGENCE REPORT\n\n"
            "## Executive Summary\n"
            "MOCK: Believe saw stable momentum across DE, UK, and FR with "
            "platform policy changes creating both opportunity and risk.\n\n"
            "## Market Trends\n"
            "MOCK: Germany remains digital-restructuring focused, the UK "
            "continues to over-index on independent discovery, and France "
            "retains a strong domestic-language streaming bias.\n\n"
            "## Platform Updates\n"
            "MOCK: Spotify, Apple Music, Deezer, YouTube Music, and TikTok "
            "all require monthly monitoring for monetization and discovery "
            "shifts.\n\n"
            "## Competitor Intelligence\n"
            "MOCK: AWAL, DistroKid, Virgin Music Group, and CD Baby remain "
            "the core competitive watchlist for Believe.\n\n"
            "## Independent Artist Economy\n"
            "MOCK: Independent artists continue gaining share, but revenue "
            "concentration and platform thresholds remain structural risks.\n\n"
            "## Market Opportunities\n"
            "MOCK: Priorities include Premium Solutions upsell, local "
            "editorial leverage, and artist development in DE, UK, and FR.\n\n"
            "## Data Sources Used\n"
            "MOCK: Believe internal KB files only. No live external retrieval "
            "was used."
        ),
        "word_count": 987,
        "sections": {
            "executive_summary": (
                "MOCK: Summary of the most important monthly developments."
            ),
            "market_trends": (
                "MOCK: Market-level updates for Germany, UK, France, and "
                "global context."
            ),
            "platform_updates": (
                "MOCK: Platform policy and product changes affecting artists."
            ),
            "competitor_intelligence": (
                "MOCK: Competitor moves, risks, and Believe implications."
            ),
            "independent_artist_economy": (
                "MOCK: Independent artist revenue and growth dynamics."
            ),
            "market_opportunities": (
                "MOCK: Recommended strategic opportunities for Believe."
            ),
            "data_sources_used": (
                "MOCK: Internal knowledge-base source references."
            ),
        },
    },
    "metadata": {
        "sections_generated": 7,
        "kb_files_used": 9,
    },
}


def build_report_request(
    year: str,
    month_name: str,
    markets: list[str],
    sections: list[str],
    selected_model: str,
    temperature: float,
) -> dict[str, object]:
    """
    Build the report-generation request object from the Gradio inputs.

    For now this returns the structured payload so the UI contract is aligned
    with the future content_pipeline.py integration.
    """
    report_request = {
        "month": month_name,
        "year": year,
        "report_period": f"{month_name} {year}",
        "markets": markets,
        "sections": sections,
        "model": selected_model,
        "temperature": temperature,
    }

    print("Generated report request:", report_request)

    return report_request


def submit_report_request(
    year: str,
    month_name: str,
    markets: list[str],
    sections: list[str],
    selected_model: str,
    temperature: float,
) -> tuple[str, str, str]:
    """
    Return a mocked content-pipeline response so the UI can be exercised
    before the real pipeline is connected.
    """
    report_request = build_report_request(
        year,
        month_name,
        markets,
        sections,
        selected_model,
        temperature,
    )

    mock_response = dict(MOCK_CONTENT_PIPELINE_RESPONSE)
    mock_response["metadata"] = {
        **MOCK_CONTENT_PIPELINE_RESPONSE["metadata"],
        "report_period": report_request["report_period"],
        "markets": report_request["markets"],
        "selected_sections": report_request["sections"],
        "selected_model": report_request["model"],
        "temperature": report_request["temperature"],
    }

    warning_message = (
        "WARNING: MOCK CONTENT PIPELINE RESPONSE ONLY. "
        "This output is hardcoded in main.py and is not generated by the "
        "real content pipeline."
    )

    return (
        warning_message,
        mock_response["report"]["full_text"],
        json.dumps(mock_response, indent=2),
    )


def select_all_sections() -> list[str]:
    """
    Select every report section in the checkbox group.
    """
    return SECTION_OPTIONS


def deselect_all_sections() -> list[str]:
    """
    Clear every report section in the checkbox group.
    """
    return []


def main():
    """
    Launch the Gradio UI for selecting report-generation inputs.

    Current purpose:
    - Fetch models suitable for text generation
    - Collect report metadata and section selection
    - Prepare the UI contract for the pipeline layer
    """
    models = get_summary_candidate_models()
    default_model = models[0] if models else None
    current_date = date.today()
    default_year = str(current_date.year)
    default_month = MONTH_OPTIONS[current_date.month - 1]

    with gr.Blocks() as demo:
        gr.Markdown("# Believe Market Intelligence Report Generator")
        gr.Markdown(
            "Choose the report month, markets, sections, and LLM settings."
        )
        gr.Markdown(
            "## WARNING: MOCK OUTPUT\n"
            "The generated report shown below is a hardcoded mock response "
            "from `main.py`. It is not coming from the real content pipeline."
        )

        with gr.Group():
            gr.Markdown("## LLM Configuration")

            model_dropdown = gr.Dropdown(
                choices=models,
                value=default_model,
                label="Model",
                info="Only models suitable for text generation are shown.",
                interactive=True,
            )

            temperature_slider = gr.Slider(
                minimum=0.0,
                maximum=1.0,
                step=0.1,
                value=0.3,
                label="Temperature",
                info="Lower = more deterministic. Higher = more creative.",
                interactive=True,
            )

        with gr.Group():
            gr.Markdown("## Report Settings")

            with gr.Row():
                year_dropdown = gr.Dropdown(
                    choices=YEAR_OPTIONS,
                    value=default_year,
                    label="Year",
                    info="Initialized to the current year.",
                    interactive=True,
                )

                month_dropdown = gr.Dropdown(
                    choices=MONTH_OPTIONS,
                    value=default_month,
                    label="Month",
                    info="Initialized to the current month.",
                    interactive=True,
                )

            market_selector = gr.CheckboxGroup(
                choices=MARKET_OPTIONS,
                value=MARKET_OPTIONS,
                label="Markets",
                info="Select one or more markets to include in the report.",
                interactive=True,
            )

            with gr.Row():
                select_all_button = gr.Button("Select All", size="sm")
                deselect_all_button = gr.Button("Deselect All", size="sm")

            section_selector = gr.CheckboxGroup(
                choices=SECTION_OPTIONS,
                value=SECTION_OPTIONS,
                label="Report Sections",
                info="Select one, several, or all sections.",
                interactive=True,
            )

            generate_button = gr.Button("Generate Report")

        warning_output = gr.Textbox(
            label="Mock Warning",
            interactive=False,
        )
        report_output = gr.Textbox(
            label="Generated Report (Mock)",
            lines=24,
            max_lines=40,
            interactive=False,
        )
        json_output = gr.Code(
            label="Mock Content Pipeline JSON",
            language="json",
            interactive=False,
        )

        generate_button.click(
            fn=submit_report_request,
            inputs=[
                year_dropdown,
                month_dropdown,
                market_selector,
                section_selector,
                model_dropdown,
                temperature_slider,
            ],
            outputs=[warning_output, report_output, json_output],
        )

        select_all_button.click(
            fn=select_all_sections,
            inputs=None,
            outputs=section_selector,
        )

        deselect_all_button.click(
            fn=deselect_all_sections,
            inputs=None,
            outputs=section_selector,
        )

    demo.launch()


if __name__ == "__main__":
    main()
