import json
from datetime import date

import gradio as gr

from content_pipeline import generate_mock_report, iterate_mock_report
from llm_integration import get_summary_candidate_models


MARKET_OPTIONS = ["DE", "UK", "FR"]
MONTH_OPTIONS = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
]
YEAR_OPTIONS = [str(year) for year in range(2024, 2031)]
REPORT_DEPTH_OPTIONS = ["short", "standard", "detailed"]
AUDIENCE_OPTIONS = [
    "strategy",
    "artist_solutions",
    "executive",
]

SECTION_OPTIONS = [
    "executive_summary",
    "market_trends",
    "platform_updates",
    "competitor_intelligence",
    "independent_artist_economy",
    "market_opportunities"
]
FEEDBACK_SCOPE_OPTIONS = ["full_report", "single_section"]


def build_report_request(
    year: str,
    month_name: str,
    markets: list[str],
    sections: list[str],
    report_depth: str,
    audience: str,
    selected_model: str,
    temperature: float,
) -> dict[str, object]:
    """
    Build the report-generation request object from the Gradio inputs.

    For now this returns the structured payload so the UI contract is aligned
    with the future content_pipeline.py integration.
    """
    report_request = {
        "month": month_name,
        "year": year,
        "report_period": f"{month_name} {year}",
        "markets": markets,
        "sections": sections,
        "report_depth": report_depth,
        "audience": audience,
        "model": selected_model,
        "temperature": temperature,
    }

    print("Generated report request:", report_request)

    return report_request


def submit_report_request(
    year: str,
    month_name: str,
    markets: list[str],
    sections: list[str],
    report_depth: str,
    audience: str,
    selected_model: str,
    temperature: float,
) -> tuple[str, str, str, str]:
    """
    Return a mocked content-pipeline response so the UI can be exercised
    before the real pipeline is connected.
    """
    report_request = build_report_request(
        year,
        month_name,
        markets,
        sections,
        report_depth,
        audience,
        selected_model,
        temperature,
    )

    mock_response = generate_mock_report(report_request)

    warning_message = (
        "WARNING: MOCK CONTENT PIPELINE RESPONSE ONLY. "
        "This output is simulated through content_pipeline.py and is not "
        "generated by the real content pipeline."
    )

    return (
        warning_message,
        json.dumps(report_request, indent=2),
        mock_response["report"]["full_text"],
        json.dumps(mock_response, indent=2),
    )


def submit_feedback_request(
    generated_report_text: str,
    report_request_json: str,
    feedback_scope: str,
    feedback_section: str,
    feedback_text: str,
) -> tuple[str, str, str]:
    """
    Send the generated report, original inputs, and user feedback to the
    mocked iterate stage in content_pipeline.py.
    """
    if not generated_report_text.strip():
        return (
            "WARNING: Generate the mock report before applying feedback.",
            "",
            "",
        )

    if not feedback_text.strip():
        return (
            "WARNING: Enter feedback before applying the iterate step.",
            "",
            "",
        )

    original_inputs = json.loads(report_request_json)
    feedback_request = {
        "original_report_text": generated_report_text,
        "original_inputs": original_inputs,
        "feedback_text": feedback_text,
        "scope": feedback_scope,
        "target_section": feedback_section,
    }
    revised_response = iterate_mock_report(feedback_request)

    warning_message = (
        "WARNING: MOCK ITERATE RESPONSE ONLY. "
        "The revised output below is simulated in content_pipeline.py and "
        "does not come from the real feedback loop yet."
    )

    return (
        warning_message,
        revised_response["report"]["full_text"],
        json.dumps(revised_response, indent=2),
    )


def select_all_sections() -> list[str]:
    """
    Select every report section in the checkbox group.
    """
    return SECTION_OPTIONS


def deselect_all_sections() -> list[str]:
    """
    Clear every report section in the checkbox group.
    """
    return []


def main():
    """
    Launch the Gradio UI for selecting report-generation inputs.

    Current purpose:
    - Fetch models suitable for text generation
    - Collect report metadata and section selection
    - Prepare the UI contract for the pipeline layer
    """
    models = get_summary_candidate_models()
    default_model = models[0] if models else None
    current_date = date.today()
    default_year = str(current_date.year)
    default_month = MONTH_OPTIONS[current_date.month - 1]

    with gr.Blocks() as demo:
        gr.Markdown("# Believe Market Intelligence Report Generator")
        gr.Markdown(
            "Choose the report month, markets, sections, and LLM settings."
        )
        gr.Markdown(
            "## WARNING: MOCK OUTPUT\n"
            "The generated report shown below is a hardcoded mock response "
            "from `content_pipeline.py`. It is not coming from the real "
            "content pipeline."
        )

        with gr.Group():
            gr.Markdown("## LLM Configuration")

            model_dropdown = gr.Dropdown(
                choices=models,
                value=default_model,
                label="Model",
                info="Only models suitable for text generation are shown.",
                interactive=True,
            )

            temperature_slider = gr.Slider(
                minimum=0.0,
                maximum=1.0,
                step=0.1,
                value=0.3,
                label="Temperature",
                info="Lower = more deterministic. Higher = more creative.",
                interactive=True,
            )

        with gr.Group():
            gr.Markdown("## Report Settings")

            with gr.Row():
                year_dropdown = gr.Dropdown(
                    choices=YEAR_OPTIONS,
                    value=default_year,
                    label="Year",
                    info="Initialized to the current year.",
                    interactive=True,
                )

                month_dropdown = gr.Dropdown(
                    choices=MONTH_OPTIONS,
                    value=default_month,
                    label="Month",
                    info="Initialized to the current month.",
                    interactive=True,
                )

            market_selector = gr.CheckboxGroup(
                choices=MARKET_OPTIONS,
                value=MARKET_OPTIONS,
                label="Markets",
                info="Select one or more markets to include in the report.",
                interactive=True,
            )

            with gr.Row():
                select_all_button = gr.Button("Select All", size="sm")
                deselect_all_button = gr.Button("Deselect All", size="sm")

            section_selector = gr.CheckboxGroup(
                choices=SECTION_OPTIONS,
                value=SECTION_OPTIONS,
                label="Report Sections",
                info="Select one, several, or all sections.",
                interactive=True,
            )

            with gr.Row():
                report_depth_dropdown = gr.Dropdown(
                    choices=REPORT_DEPTH_OPTIONS,
                    value="standard",
                    label="Report Depth",
                    info="Controls the intended output length and level of detail.",
                    interactive=True,
                )

                audience_dropdown = gr.Dropdown(
                    choices=AUDIENCE_OPTIONS,
                    value="strategy",
                    label="Audience",
                    info="Controls the framing of the output for the target reader.",
                    interactive=True,
                )

            generate_button = gr.Button("Generate Report")

        warning_output = gr.Textbox(
            label="Mock Warning",
            interactive=False,
        )
        report_request_output = gr.Code(
            label="Original Report Request JSON",
            language="json",
            interactive=False,
        )
        report_output = gr.Textbox(
            label="Generated Report (Mock)",
            lines=24,
            max_lines=40,
            interactive=False,
        )
        json_output = gr.Code(
            label="Mock Content Pipeline JSON",
            language="json",
            interactive=False,
        )

        with gr.Group():
            gr.Markdown("## Iterate / Feedback")
            gr.Markdown(
                "This is also a mock. The iterate step receives the generated "
                "text, the original report inputs, and the feedback text."
            )

            with gr.Row():
                feedback_scope_dropdown = gr.Dropdown(
                    choices=FEEDBACK_SCOPE_OPTIONS,
                    value="full_report",
                    label="Feedback Scope",
                    info="Choose whether feedback applies to the full report or a single section.",
                    interactive=True,
                )

                feedback_section_dropdown = gr.Dropdown(
                    choices=SECTION_OPTIONS,
                    value="executive_summary",
                    label="Feedback Section",
                    info="Used when the feedback scope is a single section.",
                    interactive=True,
                )

            feedback_textbox = gr.Textbox(
                label="Feedback",
                lines=4,
                placeholder="Example: Make the market trends section more specific and shorten the executive summary.",
                interactive=True,
            )

            apply_feedback_button = gr.Button("Apply Feedback")

        feedback_warning_output = gr.Textbox(
            label="Iterate Warning",
            interactive=False,
        )
        revised_report_output = gr.Textbox(
            label="Revised Report (Mock Iterate Output)",
            lines=24,
            max_lines=40,
            interactive=False,
        )
        revised_json_output = gr.Code(
            label="Mock Iterate JSON",
            language="json",
            interactive=False,
        )

        generate_button.click(
            fn=submit_report_request,
            inputs=[
                year_dropdown,
                month_dropdown,
                market_selector,
                section_selector,
                report_depth_dropdown,
                audience_dropdown,
                model_dropdown,
                temperature_slider,
            ],
            outputs=[
                warning_output,
                report_request_output,
                report_output,
                json_output,
            ],
        )

        apply_feedback_button.click(
            fn=submit_feedback_request,
            inputs=[
                report_output,
                report_request_output,
                feedback_scope_dropdown,
                feedback_section_dropdown,
                feedback_textbox,
            ],
            outputs=[
                feedback_warning_output,
                revised_report_output,
                revised_json_output,
            ],
        )

        select_all_button.click(
            fn=select_all_sections,
            inputs=None,
            outputs=section_selector,
        )

        deselect_all_button.click(
            fn=deselect_all_sections,
            inputs=None,
            outputs=section_selector,
        )

    demo.launch()


if __name__ == "__main__":
    main()
